services:
    mysql:
        container_name: "rfsim5g-mysql"
        image: mysql:8.0
        volumes:
            - ../5g_rfsimulator/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ../5g_rfsimulator/mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.71.131
    oai-amf:
        container_name: "rfsim5g-oai-amf"
        image: oaisoftwarealliance/oai-amf:ci-tmp-pr-372-26c14bcd
        environment:
            - TZ=Europe/paris
        volumes:
            - ../5g_rfsimulator/mini_nonrf_config.yaml:/openair-amf/etc/config.yaml
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.71.132
    oai-smf:
        container_name: "rfsim5g-oai-smf"
        image: oaisoftwarealliance/oai-smf:v2.1.9
        environment:
            - TZ=Europe/Paris
        volumes:
            - ../5g_rfsimulator/mini_nonrf_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.71.133
    oai-upf:
        container_name: "rfsim5g-oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.1.9
        environment:
            - TZ=Europe/Paris
        volumes:
            - ../5g_rfsimulator/mini_nonrf_config.yaml:/openair-upf/etc/config.yaml
        depends_on:
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.71.134
                interface_name: eth0
            traffic_net:
                ipv4_address: 192.168.72.134
                interface_name: eth1
    oai-ext-dn:
        privileged: true
        container_name: rfsim5g-oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:focal
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.72.134 dev eth0; sleep infinity"
        depends_on:
            - oai-upf
        networks:
            traffic_net:
                ipv4_address: 192.168.72.135
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.72.134"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-cucp-0:
        image: ${REGISTRY:-oaisoftwarealliance}/${GNB_IMG:-oai-gnb}:${TAG:-develop}
        container_name: rfsim5g-oai-cucp-0
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --telnetsrv --telnetsrv.shrmod ci
                                    --telnetsrv.listenaddr 192.168.71.150
                                    --gNBs.[0].nr_cellid 0
                                    --log_config.global_log_options level,nocolor,time
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        volumes:
          - ../../conf_files/neighbour-config.conf:/opt/oai-gnb/etc/neighbour-config.conf
          - ../../conf_files/gnb-cucp.sa.e1-ho-n2.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5

    oai-cuup-0:
        image: ${REGISTRY:-oaisoftwarealliance}/${NRCUUP_IMG:-oai-nr-cuup}:${TAG:-develop}
        container_name: rfsim5g-oai-cuup-0
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.71.150
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cuup 192.168.71.151
                                    --gNBs.[0].NETWORK_INTERFACES.GNB_IPV4_ADDRESS_FOR_NGU 192.168.71.151
                                    --gNBs.[0].local_s_address 192.168.71.151
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-cucp-0
        networks:
            public_net:
                ipv4_address: 192.168.71.151
        volumes:
            - ../../conf_files/gnb-cuup.sa.f1.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-cuup"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5


    oai-du-0:
        image: ${REGISTRY:-oaisoftwarealliance}/${GNB_IMG:-oai-gnb}:${TAG:-develop}
        container_name: rfsim5g-oai-du-0
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim
                                    --log_config.global_log_options level,nocolor,time
                                    --gNBs.[0].nr_cellid 0
                                    --telnetsrv --telnetsrv.listenaddr 192.168.71.171
                                    --telnetsrv.shrmod ci
                                    --rfsimulator.serveraddr 192.168.71.190
                                    --gNBs.[0].servingCellConfigCommon.[0].ra_ResponseWindow 5
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0
        depends_on:
            - oai-cucp-0
        networks:
            public_net:
                ipv4_address: 192.168.71.171
        volumes:
            - ../../conf_files/neighbour-config.conf:/opt/oai-gnb/etc/neighbour-config.conf
            - ../../conf_files/gnb-du.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue:
        image: ${REGISTRY:-oaisoftwarealliance}/${NRUE_IMG:-oai-nr-ue}:${TAG:-develop}
        container_name: rfsim5g-oai-nr-ue
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --rfsimulator.serveraddr server
                                    --band 78 -C 3619200000 -r 106 --numerology 1 --ssb 516
                                    --uicc0.imsi 208990100001100
                                    --log_config.global_log_options level,nocolor,time
        networks:
            public_net:
                ipv4_address: 192.168.71.190
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ../../conf_files/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-cucp-1:
        image: ${REGISTRY:-oaisoftwarealliance}/${GNB_IMG:-oai-gnb}:${TAG:-develop}
        container_name: rfsim5g-oai-cucp-1
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --telnetsrv --telnetsrv.shrmod ci
                                    --telnetsrv.listenaddr 192.168.71.180
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.71.180
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cuup 192.168.71.181
                                    --gNBs.[0].local_s_address 192.168.71.180
                                    --gNBs.[0].remote_s_address 192.168.71.181
                                    --gNBs.[0].gNB_ID 0xb00
                                    --gNBs.[0].nr_cellid 1
                                    --gNBs.[0].NETWORK_INTERFACES.GNB_IPV4_ADDRESS_FOR_NG_AMF 192.168.71.180
                                    --gNBs.[0].NETWORK_INTERFACES.GNB_IPV4_ADDRESS_FOR_NGU 192.168.71.180
                                    --log_config.global_log_options level,nocolor,time
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.71.180
        volumes:
          - ../../conf_files/neighbour-config.conf:/opt/oai-gnb/etc/neighbour-config.conf
          - ../../conf_files/gnb-cucp.sa.e1-ho-n2.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5

    oai-cuup-1:
        image: ${REGISTRY:-oaisoftwarealliance}/${NRCUUP_IMG:-oai-nr-cuup}:${TAG:-develop}
        container_name: rfsim5g-oai-cuup-1
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.71.180
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cuup 192.168.71.181
                                    --gNBs.[0].NETWORK_INTERFACES.GNB_IPV4_ADDRESS_FOR_NGU 192.168.71.181
                                    --gNBs.[0].local_s_address 192.168.71.181
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-cucp-0
        networks:
            public_net:
                ipv4_address: 192.168.71.181
        volumes:
            - ../../conf_files/gnb-cuup.sa.f1.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-cuup"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5

    oai-du-1:
        image: ${REGISTRY:-oaisoftwarealliance}/${GNB_IMG:-oai-gnb}:${TAG:-develop}
        container_name: rfsim5g-oai-du-1
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim
                                    --rfsimulator.serveraddr 192.168.71.190
                                    --log_config.global_log_options level,nocolor,time
                                    --gNBs.[0].gNB_DU_ID 1234
                                    --gNBs.[0].gNB_ID 0xb00
                                    --gNBs.[0].nr_cellid 1
                                    --gNBs.[0].servingCellConfigCommon.[0].physCellId 1
                                    --gNBs.[0].servingCellConfigCommon.[0].absoluteFrequencySSB 621312
                                    --gNBs.[0].servingCellConfigCommon.[0].dl_absoluteFrequencyPointA 620040
                                    --MACRLCs.[0].local_n_address 192.168.71.182
                                    --MACRLCs.[0].remote_n_address 192.168.71.180
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0
        depends_on:
            - oai-cucp-1
        networks:
            public_net:
                ipv4_address: 192.168.71.182
        volumes:
            - ../../conf_files/neighbour-config.conf:/opt/oai-gnb/etc/neighbour-config.conf
            - ../../conf_files/gnb-du.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        driver: bridge
        name: rfsim5g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-public"
    traffic_net:
        driver: bridge
        name: rfsim5g-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-traffic"
