apiVersion: v2
name: aurora
description: Aurora telemetry sidecar for OAI RAN (CU/DU/gNB)
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - Aurora
  - Telemetry
  - RAN
  - 5G
  - CU
  - DU
  - gNB
  - Sidecar
sources:
  - https://gitlab.eurecom.fr/oai/openairinterface5g
maintainers:
  - name: OPENAIRINTERFACE
    email: contact@openairinterface.org
